from __future__ import annotations

CMD_SYNC_SETUP = "SYNC_SETUP"
CMD_SQUAD_MOVE = "SQUAD_MOVE"
CMD_SQUAD_WARP = "SQUAD_WARP"
CMD_SQUAD_APPROACH = "SQUAD_APPROACH"
CMD_SQUAD_ATTACK = "SQUAD_ATTACK"
CMD_SQUAD_PROPULSION = "SQUAD_PROPULSION"
CMD_SQUAD_PREFOCUS = "SQUAD_PREFOCUS"
CMD_SQUAD_CANCEL_PREFOCUS = "SQUAD_CANCEL_PREFOCUS"
CMD_SQUAD_CLEAR_FOCUS = "SQUAD_CLEAR_FOCUS"
CMD_SQUAD_LEADER_SPEED_LIMIT = "SQUAD_LEADER_SPEED_LIMIT"
CMD_INDUCE_SQUAD_AT = "INDUCE_SQUAD_AT"
CMD_INDUCE_FLEET_AT = "INDUCE_FLEET_AT"

SQUAD_FOCUS_COMMANDS = (
    CMD_SQUAD_PREFOCUS,
    CMD_SQUAD_CANCEL_PREFOCUS,
    CMD_SQUAD_CLEAR_FOCUS,
)
