from __future__ import annotations

CMD_SYNC_SETUP = "SYNC_SETUP"
CMD_ASSIGN_SHIPS_TO_SQUAD = "ASSIGN_SHIPS_TO_SQUAD"
CMD_SQUAD_MOVE = "SQUAD_MOVE"
CMD_SQUAD_WARP = "SQUAD_WARP"
CMD_SQUAD_USE_GATE = "SQUAD_USE_GATE"
CMD_SQUAD_APPROACH = "SQUAD_APPROACH"
CMD_SQUAD_NAVIGATE = "SQUAD_NAVIGATE"
CMD_SQUAD_ATTACK = "SQUAD_ATTACK"
CMD_SQUAD_DRONE_ATTACK = "SQUAD_DRONE_ATTACK"
CMD_SQUAD_FIGHTER_ATTACK = "SQUAD_FIGHTER_ATTACK"
CMD_SQUAD_FIGHTER_ABILITY = "SQUAD_FIGHTER_ABILITY"
CMD_SQUAD_LAUNCH_DRONES = "SQUAD_LAUNCH_DRONES"
CMD_SQUAD_LAUNCH_FIGHTERS = "SQUAD_LAUNCH_FIGHTERS"
CMD_SQUAD_RECALL_DEPLOYABLES = "SQUAD_RECALL_DEPLOYABLES"
CMD_SQUAD_PROPULSION = "SQUAD_PROPULSION"
CMD_SQUAD_PREFOCUS = "SQUAD_PREFOCUS"
CMD_SQUAD_CANCEL_PREFOCUS = "SQUAD_CANCEL_PREFOCUS"
CMD_SQUAD_CLEAR_FOCUS = "SQUAD_CLEAR_FOCUS"
CMD_SQUAD_LEADER_SPEED_LIMIT = "SQUAD_LEADER_SPEED_LIMIT"
CMD_INDUCE_SQUAD_AT = "INDUCE_SQUAD_AT"
CMD_INDUCE_FLEET_AT = "INDUCE_FLEET_AT"
CMD_SET_MODULE_CHARGE_LOCK = "SET_MODULE_CHARGE_LOCK"
CMD_CLEAR_MODULE_CHARGE_LOCK = "CLEAR_MODULE_CHARGE_LOCK"
CMD_SET_FLEET_MODULE_CHARGE = "SET_FLEET_MODULE_CHARGE"
CMD_SET_MODULE_MANUAL_MODE = "SET_MODULE_MANUAL_MODE"
CMD_SET_MODULE_TARGET_MODE = "SET_MODULE_TARGET_MODE"
CMD_SYNC_MODULE_CONTROLS = "SYNC_MODULE_CONTROLS"

SQUAD_FOCUS_COMMANDS = (
    CMD_SQUAD_PREFOCUS,
    CMD_SQUAD_CANCEL_PREFOCUS,
    CMD_SQUAD_CLEAR_FOCUS,
)
